### ISSUE TITLE
Arch User Repository.

### ISSUE THREAD

**Issue by begin-theadventure** [AnActualEmerald/papa#10]
Would it be possible to add papa to the AUR?

**Comment by AnActualEmerald** [comment]
I can look into it, I've never put a package on there but it should be doable

**Comment by begin-theadventure** [comment]
I'll try to make a PGKBUILD.

**Comment by begin-theadventure** [comment]
Okay. I managed to create two PKGBUILDS!
A standard one with the source code for compiling and another one - binary/precompiled.
Would you like me to send them to a [maintainer](https://github.com/FabioLolix/PKGBUILD), or would you prefer to submit them yourself to the AUR?

**Comment by AnActualEmerald** [comment]
I guess I don't really have a strong preference one way or another, I am pretty busy though lmao

**Comment by begin-theadventure** [comment]
All right.

**Comment by begin-theadventure** [comment]
I figured it out and added papa + papa-bin to the AUR.
