### ISSUE TITLE
[Feature request] Installing without agreeing.

### ISSUE THREAD

**Issue by begin-theadventure** [AnActualEmerald/papa#11]
There could be a `-y` flag  for installing without having to type y and click enter every time. Something like this:
```
papa install -y mod
Updating package index... Done!
Installing:

	 MOD

Will download ~00.00 MIB (compressed) automatically.
Downloading modlink
```

**Comment by AnActualEmerald** [comment]
This should already be the case v2.2.0, is it not working for you?

**Comment by begin-theadventure** [comment]
🤣
I tested it wrong, sorry/or used an older release, not sure.
Thanks for the project btw, no bloat 💪
