### ISSUE TITLE
Allow to use cache with force.

### ISSUE THREAD

**Issue by begin-theadventure** [AnActualEmerald/papa#16]
In the version 2.2.0, when I used `--force` it used the cached files, but now when I do that, it downloads the files again.
Would it be possible to add a flag that would allow this? Or does such a flag already exist?

**Comment by AnActualEmerald** [comment]
I can split disabling cache into its own flag, probably makes more sense that way anyways

**Comment by begin-theadventure** [comment]
Yeah, something like `--no-cache`.

**Comment by AnActualEmerald** [comment]
Added in 6c3e55a

**Comment by begin-theadventure** [comment]
Thank you for your work!
