### ISSUE TITLE
[BUG?] Mods can't be installed due to errors.

### ISSUE THREAD

**Issue by begin-theadventure** [AnActualEmerald/papa#17]
**Describe the bug**
After version 2.2.0 some mods can't be installed now, even with `--force`.

_Not a directory (os error 20)_
blacklight.mach_daddy
blacklight.cloak_shadow

_Error stripping directory prefix prefix not found
Is the mod formatted correctly?_
CNS144.octane_knife_Replace_melee
EXRILL.Exrills_Ion_Omega_Voice
Creamy_jpg.Better_Cooper

I was able to force install them with 2.2.0:
`papa install --force mach_daddy cloak_shadow octane_knife_Replace_melee Exrills_Ion_Omega_Voice Better_Cooper`
3.0.1 just spells out the error and fails, even with `--force`.

I think `--force` should still install the files despite the errors.

**Comment by AnActualEmerald** [comment]
I can look into allowing misformatted mods to be installed with force enabled, but I haven't been able to track down what causes the `not a directory` error (though I'm pretty sure it also has to do with formatting of the mod package)

The easiest fix for this would be to yell at the mod authors and have them package their stuff correctly lol

**Comment by AnActualEmerald** [comment]
I think this should be solved in b94a49e, `--force` will now ignore errors and continue though it won't actually install the mod that caused the error. If that's the behavior you want I'd have to adjust [thermite](https://github.com/anactualemerald/thermite) itself, though really people should just learn how to format their mods.
