### ISSUE TITLE
[Question] Mods list.

### ISSUE THREAD

**Issue by begin-theadventure** [AnActualEmerald/papa#20]
Where's the list of mods saved now?
In 2.2.0 it was saved in `.papa.ron`, but version 3 changed that, "It no longer uses the index file to track mods."

**Comment by AnActualEmerald** [comment]
Right now I get the list by reading the mod directory and checking for subdirectories with a `mod.json` file and a `thunderstore_author.txt` file, but I do plan to allow exporting and importing that list in the future. The change was made for compatibility with the other mod managers which should follow the same rules now.

**Comment by begin-theadventure** [comment]
> but I do plan to allow exporting and importing that list in the future

Great.
