### ISSUE TITLE
[Feature] Disable/enable all flags.

### ISSUE THREAD

**Issue by begin-theadventure** [AnActualEmerald/papa#21]
`papa disable --all` - would disable all mods except Northstar's.
`papa enable --all`
Disabling all would be useful, for example, when you wanted to test a mod faster without having to load every mod you have for normal matches.

**Comment by AnActualEmerald** [comment]
added in aa40d26

**Comment by begin-theadventure** [comment]
Awesom!!

**Comment by begin-theadventure** [comment]
Awesome!!
