### ISSUE TITLE
[BUG] Old folders are left in case of a name change.

### ISSUE THREAD

**Issue by begin-theadventure** [AnActualEmerald/papa#22]
<p align="center">Description</p>
You installed version 1.0.0 and the mod was in a folder named "X-Y-Z", then 1.0.1 is released, you update, but the folder is in a folder named "XYZ", Papa doesn't check and delete the folder, but just installs the new update.

This results in having two versions of the same mod, but with different versions.

**Comment by begin-theadventure** [comment]
Perhaps this could be solved with ~~#19~~ (_edit_, sorry) #18?

**Comment by AnActualEmerald** [comment]
fixed in 97351f40798fad2685aa9f78d2962853e37c9b55
